### ISSUE TITLE
learning phase

### ISSUE THREAD

**Issue by xin71** [eugenelet/Meta-rPPG#1]
Thanks for releasing the code for the meta-rPPG paper! Very interesting paper!

I am wondering where is the code for the **learning phase** described in the algrotihm 1 (Training of Meta-Learner)? Is it 'def fewshot_learning' whic is currently unifished? If so, does the trainng pipeline work without it? 

Thanks!

**Comment by eugenelet** [comment]
Hi Xin,

Glad that we Thanks for taking interest in our work!

The **adaptation phase** and **learning phase** corresponds to L69 and L71 of `train.py` respectively. Comments are added in our latest commit.

Let us know if this answers your question.

**Comment by eugenelet** [comment]
Hi Xin,

You're mostly welcome!

The latest commit resolves this issue. We missed that line during the preparation of the code for public use. Thanks for pointing it out.

**Comment by xin71** [comment]
> Hi Xin,
> 
> You're mostly welcome!
> 
> The latest commit resolves this issue. We missed that line during the preparation of the code for public use. Thanks for pointing it out.

Thanks Eugene. That makes a lot more sense. BTW, it seems like you guys also ran the learning phase twice since you set `opt.per_iter_task ` to be 3. I am curious why is it 3?

**Comment by eugenelet** [comment]
Hi Xin, that's just an ad-hoc decision used to sample 3 consecutive segments from a sequence of frames. We didn't tune `opt.per_iter_task` to fine-tune performance, further tuning might give better results.

**Comment by xin71** [comment]
Thanks!

**Comment by eugenelet** [comment]
You're welcome!
