### ISSUE TITLE
Where do the benchmarks for other methods on UBFC come from?

### ISSUE THREAD

**Issue by sdll** [eugenelet/Meta-rPPG#3]
<img width="796" alt="Screen Shot 2020-07-27 at 16 35 57" src="https://user-images.githubusercontent.com/17913919/88548063-40578180-d027-11ea-8008-e78ce4960b64.png">
In the paper there is a comparison of Meta-rPPG with other methods, but not all of the referenced authors list MAE, RMSE and r on UBFC. Could you please tell me whether you have trained these models on your own data as well?

**Comment by eugenelet** [comment]
Hi, 

The results are borrowed directly from Ref. 4, we did not reproduce their work from scratch. Note that some of the cited work doesn't require any form of training.
